version: "3.9"

services:
  db:
    image: postgres:16
    container_name: todolist_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123ediwow
      POSTGRES_DB: softdev3-final
    ports:
      - "5431:5432" # host:container (use 5431 to avoid conflict with local postgres)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: node:20
    container_name: todolist_backend
    working_dir: /usr/src/app
    command: sh -c "npm install && npx prisma migrate deploy && npx prisma generate && npm run dev"
    volumes:
      - ./BE/my-express-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:123ediwow@db:5432/softdev3-final?schema=public
      - NODE_ENV=development
      - PORT=3000
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    image: node:20
    container_name: todolist_frontend
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./FE/my-react-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: